sphere:
    refinement_order: 3
    center: [0.0, 0.0, 0.0]
refinement_targets:
  - target_code: "SHSA"
    refinement_order: 6
    refinement_type: "uniform"
    buffer_factor: 200
gzip: true
save_layers: false
split_layers: true
output:
  filename: "SHSA"