sphere:
    refinement_order: 3
    center: [0.0, 0.0, 0.0]
refinement_targets:
  - target_code: "EURO"
    refinement_order: 6
    refinement_type: "uniform"
    buffer_factor: 400
gzip: true
save_layers: true